name: Check License Lines

on: [pull_request]

jobs:
  check-license-lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: License Checker
      uses: ddevassy/license_checker@master
