name: Manage versions

on: [push, pull_request]

jobs:
  bump:
    runs-on: ubuntu-latest
   
    steps:
      # Checkout action is required
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Bump Versions
        uses: mddevassy/version-bumper@master
        with:
          scheme: semantic
          username: NTABot
          email: NTABot@logitech.com
          version-file: "./VERSION"
          files: >
            [
             "./VERSION"
            ] 
          rules: '[{"trigger": "commit", "bump": "build", "branch": "master", "tag": true},{"trigger": "manual", "bump": "minor", "reset": "build", "branch": "master", "tag": true} ]'
          github-token: ${{ secrets.GITHUB_TOKEN }}
