name: Manage versions
on: [push]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v1
        with:
          node-version: '16'      
      - name: Version Bumper
        uses: ddevassy/version-bumper
        with:
          options-file: "./.github/workflows/options.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
